# Generated by Django 4.1.10 on 2023-07-15 15:04

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RssFeedAiSettings',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('keywords', djongo.models.fields.JSONField(default=[])),
                ('negative_keywords', djongo.models.fields.JSONField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name='RSSFeedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_source_name', models.CharField(max_length=100)),
                ('feed_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RssFeedAiContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('preamble', models.CharField(max_length=2500)),
                ('text', models.CharField(max_length=5000)),
                ('article_url', models.URLField()),
                ('pub_date', models.DateTimeField()),
                ('image_url', models.URLField()),
                ('source_feed_id', models.CharField(max_length=500, unique=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airss.rssfeedsource')),
            ],
        ),
    ]
