# Generated by Django 4.1.10 on 2024-04-15 15:40

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RssFeedSource',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('source_url', models.URLField()),
                ('require_login', models.BooleanField(default=False)),
                ('summarize_from_rss_feed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RssModule',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('slang', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RssSource',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('rss_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airss.rssmodule')),
                ('sources', models.ManyToManyField(to='airss.rssfeedsource')),
            ],
        ),
        migrations.CreateModel(
            name='RssSummarizedContent',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('preamble', models.CharField(max_length=2500)),
                ('text', models.CharField(max_length=5000)),
                ('article_url', models.URLField()),
                ('pub_date', models.DateTimeField()),
                ('image_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rss_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airss.rssmodule')),
                ('rss_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airss.rsssource')),
            ],
        ),
        migrations.CreateModel(
            name='RssModuleSettings',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('manual_convert', models.BooleanField(default=False)),
                ('keywords', djongo.models.fields.JSONField(default=[])),
                ('negative_keywords', djongo.models.fields.JSONField(default=[])),
                ('rss_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airss.rssmodule')),
            ],
        ),
        migrations.CreateModel(
            name='FetchedFeedItem',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('feed_id', models.TextField()),
                ('feed_item_url', models.URLField()),
                ('feed_content', models.TextField()),
                ('allowed_to_summarize', models.BooleanField(default=False)),
                ('rss_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airss.rssmodule')),
                ('rss_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airss.rsssource')),
            ],
        ),
    ]
