# Generated by Django 4.1.10 on 2024-04-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airss', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fetchedfeeditem',
            name='allowed_to_summarize',
        ),
    ]
