# Generated by Django 4.1.10 on 2023-07-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airss', '0002_rssfeedaicontent_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeedaicontent',
            name='image_url',
            field=models.TextField(),
        ),
    ]
