# Generated by Django 4.1.10 on 2024-04-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airss', '0002_remove_fetchedfeeditem_allowed_to_summarize'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchedfeeditem',
            name='allowed_to_summarize',
            field=models.BooleanField(default=True),
        ),
    ]
