# Generated by Django 4.1.10 on 2024-04-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airss', '0003_fetchedfeeditem_allowed_to_summarize'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeedsource',
            name='rss_module',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='airss.rssmodule'),
        ),
    ]
