# Generated by Django 4.1.10 on 2023-07-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airss', '0003_alter_rssfeedaicontent_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeedsource',
            name='require_login',
            field=models.BooleanField(default=False),
        ),
    ]
