# Generated by Django 4.1.10 on 2024-04-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airss', '0005_remove_rssfeedsource_rss_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeedsource',
            name='source_name',
            field=models.TextField(default=''),
        ),
    ]
