# Generated by Django 4.1.10 on 2024-04-30 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airss', '0007_fetchedfeeditem_feed_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsssummarizedcontent',
            name='rss_module',
        ),
        migrations.RemoveField(
            model_name='rsssummarizedcontent',
            name='rss_source',
        ),
        migrations.AddField(
            model_name='rsssummarizedcontent',
            name='fetched_feed_item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='airss.fetchedfeeditem'),
        ),
    ]
