# Generated by Django 4.1.10 on 2024-05-02 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airss', '0008_remove_rsssummarizedcontent_rss_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchedfeeditem',
            name='rss_feed_source',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='airss.rssfeedsource'),
        ),
    ]
