# Generated by Django 4.1.10 on 2024-05-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airss', '0011_fetchedfeeditem_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchedfeeditem',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
