# Generated by Django 4.1.10 on 2024-05-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airss', '0012_alter_fetchedfeeditem_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchedfeeditem',
            name='image_url',
            field=models.TextField(default=''),
        ),
    ]
