# Generated by Django 4.1.10 on 2024-05-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airss', '0013_fetchedfeeditem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeedsource',
            name='require_keywords_verification',
            field=models.BooleanField(default=True),
        ),
    ]
