# Generated by Django 4.1.10 on 2024-05-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airss', '0014_rssfeedsource_require_keywords_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchedfeeditem',
            name='feed_content',
            field=models.TextField(default=''),
        ),
    ]
