# Generated by Django 4.1.10 on 2024-05-10 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airss', '0016_alter_fetchedfeeditem_feed_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssmodulesettings',
            name='rss_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='airss.rssmodule'),
        ),
    ]
