# Generated by Django 4.1.10 on 2024-05-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airss', '0018_alter_fetchedfeeditem_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchedfeeditem',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
